export const Stories =[
    {
        id:1,
        title:'Boku no Hero Academia',
        description: 'La historia está ambientada en la época actual, excepto que las personas con poderes especiales se han vuelto comunes en todo el mundo. Un chico llamado Izuku Midoriya no tiene poderes, pero sueña tenerlos',
        image: require('../../assets/ImagesStories/boku-no-hero.png'),
        rating: 5,
        category: 'manga',
        genres: ['Acción', 'Comedia', 'Vida Escolar', 'Superpoderes', 'Ciencia Ficción', 'Artes Marciales'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:2,
        title:'Kimetsu no Yaiba',
        description: 'Tanjirou es el hijo mayor en una familia quien perdió a su padre. Un día, va de visita a otro pueblo para vender carbón, y termina quedándose a pasar la noche en la casa de un lugareño, ya que abunda el rumor de un demonio que ronda por las montañas por la noche. Cuando vuelve a casa al siguiente día, una tragedia lo estaba esperando.',
        image: require('../../assets/ImagesStories/kimetsu.png'),
        rating: 5,
        category: 'manga',
        genres: ['Acción', 'Demonios', 'Sobrenatural', 'Aventura', 'Fantasia', 'Tragedia', 'Historia'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:3,
        title:'One Piece',
        description: 'Hace veintidós años, el legendario pirata, Gold Roger fue ejecutado. Sus últimas palabras fueron que su tesoro conocido como "One Piece" estaba escondido en algún lugar dentro del vasto océano conocido como el "Grand Line" (Gran Ruta Marítima). Esto dio inicio a la Era de los Piratas. Ahora, se nos presenta a Monkey D. Luffy, un joven que, inspirado por su ídolo de la infancia emprende su viaje en busca del One Piece, con el objetivo de convertirse en el Rey de los Piratas.',
        image:require('../../assets/ImagesStories/one-piece.png'),
        rating: 5,
        category: 'manga',
        genres: ['Acción', 'Comedia', 'Artes Marciales', 'Aventura', 'Superpoderes', 'Misterio', 'Sobrenatural'],
        status: 'Publicándose',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:4,
        title:'Chainsaw Man',
        description: 'Cuando su padre murió, Denji se vio obligado a saldar una gran deuda y no había forma de pagarla. Pero gracias a la ayuda de un Demonio Perro que salvó llamado Pochita, Denji es capaz de sobrevivir convirtiéndose en un Cazador de demonios a sueldo, haciendo trabajos para los Yakuza. Los poderes motosierra de Pochita son útiles contra estos poderosos demonios. Y cuando Denji termina siendo asesinado por un demonio, Pochita se sacrifica para revivirlo. Pero ahora Denji ha renacido como una especie de extraño híbrido Demonio-Humano. ¡Ahora es Chainsaw Man! Después de su transformación, es reclutado rápidamente y obligado a unirse a los Cazadores de Demonios de Seguridad Pública bajo amenaza de exterminio ya que técnicamente es un Demonio. Ahora que vive cómodamente por primera vez en su vida, Denji lucha por determinar sus sueños y establecer relaciones significativas mientras mata demonios y trabaja junto a otros excéntricos cazadores.s',
        image: require('../../assets/ImagesStories/chainsawman.png'),
        rating: 5,
        category: 'manga',
        genres: ['Acción', 'Comedia', 'Horror', 'Demonios', 'Fantasia', 'Sobrenatural'],
        status: 'Publicándose',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:5,
        title:'La Vida Después de la Muerte',
        description: 'El Rey Grey tiene una fuerza, riqueza y prestigio incomparables en un mundo gobernado por la habilidad marcial. Sin embargo, la soledad se mantiene muy por detrás de aquellos con gran poder. Debajo del glamoroso exterior de un poderoso rey acecha el caparazón del hombre, desprovisto de propósito y voluntad. Reencarnado en un nuevo mundo lleno de magia y monstruos, el rey tiene una segunda oportunidad de revivir su vida. Sin embargo, corregir su error pasado no será su único desafío. Debajo de la paz y la prosperidad del nuevo mundo hay una corriente subterránea que amenaza con destruir todo para lo que ha trabajado, cuestionando su papel y la razón para nacer de nuevo.',
        image: require('../../assets/ImagesStories/la-vida-despues-de-la-muerte.png'),
        rating: 5,
        category: 'manwha',
        genres: ['Acción', 'Comedia', 'Aventura', 'Drama', 'Magia', 'Superpoderes', 'Reencarnación'],
        status: 'Publicándose',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:6,
        title:'El Extra que Nunca Muere',
        description: 'En el exitoso juego [Demon War 3], hay "extras" que mueren todos los días de todas las formas posibles. Pero a pesar de no contribuir lo más mínimo al juego, un extra llamado Evan D. Shelden tiene una escena de muerte con infografía exclusiva que robó el amor del equipo de producción. Maldita sea, ¿no es ese el nombre que recibí cuando me reencarné en este mundo del juego? Yo, alguien que no es el protagonista y un extra que tiene demasiadas muertes para contarlas, ¡debo sobrevivir a toda costa!',
        image: require('../../assets/ImagesStories/extra.png'),
        rating: 5,
        category: 'manwha',
        genres: ['Fantasia', 'Harem', 'Aventura', 'Drama', 'Magia', 'Reencarnación'],
        status: 'Publicándose',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:7,
        title:'Skeleton Soldier',
        description: 'Su único propósito era proteger a su ama. Y sin embargo, no tenía el poder para protegerla. Pero el destino tiene preparado más para él en el futuro, ya que tiene otra oportunidad de proteger a su maestra y cambiar su destino.',
        image: require('../../assets/ImagesStories/skeleton-soldier.png'),
        rating: 5,
        category: 'manwha',
        genres: ['Fantasia', 'Acción', 'Aventura', 'Tragedia', 'Magia', 'Sobrenatural', 'Reencarnación'],
        status: 'Publicándose',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:8,
        title:'Blooming sequence',
        description: 'De repente, en la fiesta de apertura, Hyun toma la mano de la novata Ha-Young, que ya se cae de lo ebria. Desde entonces, Hyun está deseando tener a Ha Young como parte de su club... Un pequeño club de cine. Una nueva secuencia comienza para Hyun, la presidenta de Sineo, quien siempre ha sido malinterpretada por su feroz aspecto.',
        image: require('../../assets/ImagesStories/Blooming.png'),
        rating: 5,
        category: 'manwha',
        genres: ['Girls Love', 'Romance', 'Comedia'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:9,
        title:'2099 Alpha',
        description: '80 years ago, the Marvel Universe was born. 80 years from now, will it die?! THE FUTURE IS IN PERIL! Events of AMAZING SPIDERMAN have been leading to this for months. Something is happening in 2099 that spans Nueva York and beyond and will shake up the official Marvel Future forever. This is not a drill!',
        image: require('../../assets/ImagesStories/2099Alpha.jpg'),
        rating: 5,
        category: 'comic',
        genres: ['Acción', 'Aventura', 'Superpoderes', 'Ciencia Ficción'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:10,
        title:'10 Years to Death',
        description: 'The Shawshank Redemption meets The Sixth Sense, inspired by an eerily bone-chilling true story. A newly-hired prison guard, a notorious mass murderer finally incarcerated for his crimes, and the death that binds them together. What happens when the murdered becomes the murderer? A prestige format "One-Shock" featuring top creative talent, 10 YEARS TO DEATH is a horrific, unnerving tale conceived and written by Aaron Douglas ("Chief" from the iconic TV series Battlestar Galactica), and drawn by Cliff Richards (SHOCK, Buffy the Vampire Slayer).',
        image: require('../../assets/ImagesStories/10YearsOfDeath.jpg'),
        rating: 5,
        category: 'comic',
        genres: ['Sobrenatural'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:11,
        title:'12 September',
        description: 'Duncan Campbell is an NSA agent, historian and Middle East specialist. His life changes on September 6, 2001: he loses the woman he loves, is betrayed by his superiors and finds himself plunged into the heart of a medieval conflict that history books have never mentioned... He can only count on his good knowledge of the Islamic world and 15th century Europe to try to avoid the annihilation of two civilizations by trying to find the path that leads to reconciliation and peace between peoples... Here is a fascinating alternate history through which Roger Seiter and Simone Gabrielli return to the origins of a conflict that has been raging in two worlds for centuries, to try to understand, but also to dream of peace.',
        image: require('../../assets/ImagesStories/12September.jpg'),
        rating: 5,
        category: 'comic',
        genres: ['Fantasia'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
    {
        id:12,
        title:'1949',
        description: 'By day, Detective Blank is a cop on the trail of a vicious serial killer in the year 1949. But when she sleeps, Blank lives a different life-two hundred years in the future. Is Detective Blank next on the killers list? Her dreams may hold the key to the case, if only she can remember them in time. The danger mounts and the suspense builds as the detective closes in, in this genre-bending sci-fi noir thriller. For Detective Blank, to catch the killer will mean facing her greatest mystery-herself. Collects the entire story of Paklis: 1949, as originally published in Paklis #5-7',
        image: require('../../assets/ImagesStories/1949.jpg'),
        rating: 5,
        category: 'comic',
        genres: ['Ciencia Ficción', 'Crimen'],
        status: 'Finalizado',
        chapters: ['Capítulo 1', 'Capítulo 2', 'Capítulo 3'],
    },
]